services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: happyhour
      POSTGRES_PASSWORD: happyhour
      POSTGRES_DB: happyhour
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
